In [2]:
#Clone the Dataset
from datasets import load_dataset
dataset = load_dataset("ainlpml/english-hindi")

eng.txt:   0%|          | 0.00/1.01M [00:00<?, ?B/s]

hin.txt:   0%|          | 0.00/2.45M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/20000 [00:00<?, ? examples/s]

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text'],
        num_rows: 20000
    })
})

In [4]:
dataset['train'][0:5]

{'text': ["However, Paes, who was partnering Australia's Paul Hanley, could only go as far as the quarterfinals where they lost to Bhupathi and Knowles ",
  'Whosoever desires the reward of the world, with Allah is the reward of the world and of the Everlasting Life. Allah is the Hearer, the Seer. ',
  '"The value of insects in the biosphere is enormous because they outnumber all other living groups in measure of species richness. ',
  'Mithali To Anchor Indian Team Against Australia in ODIs ',
  'After the assent of the Honble President on 8thSeptember, 2016, the 101thConstitutional Amendment Act, 2016 came into existence ']}

In [5]:
import pandas as pd

In [6]:
# Load the Data into Google Sheets
df = pd.DataFrame(dataset['train'])
df.head()

                                                text
0  However, Paes, who was partnering Australia's ...
1  Whosoever desires the reward of the world, wit...
2  "The value of insects in the biosphere is enor...
3  Mithali To Anchor Indian Team Against Australi...
4  After the assent of the Honble President on 8t...

In [7]:
df

                                                    text
0      However, Paes, who was partnering Australia's ...
1      Whosoever desires the reward of the world, wit...
2      "The value of insects in the biosphere is enor...
3      Mithali To Anchor Indian Team Against Australi...
4      After the assent of the Honble President on 8t...
...                                                  ...
19995  इन चंद, चुनिंदा शब्दों से बुद्धिमान राजा सुलैम...
19996  पुलिस ने युवकों का पीछा कर दो युवकों को हिरासत...
19997  में मुर्गीपालन से प्राप्त मांस तथा गाद का अनुम...
19998  सबसे पहले ऑफिशियल वेबसाइट education. rajasthan...
19999  डिस्क्लेमर : अनिल अंबानी के रिलायंस ग्रुप ने N...

[20000 rows x 1 columns]

In [8]:
# Hindi and English Dataset spliting:
midpoint =len(df)//2
# midpoint

english_data = df['text'].iloc[:midpoint].reset_index(drop=True)
# english_data

hindi_data = df['text'].iloc[midpoint:].reset_index(drop=True)
# hindi_data

processed_df = pd.DataFrame({
    #coloum1
    'English Sentences':english_data,

    #coloum2
    'Hindi Sentences':hindi_data
}
)

processed_df

,English Sentences,Hindi Sentences
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ..."
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व..."
...,...,...
9995,"With these few, well - chosen words, wise King...","इन चंद, चुनिंदा शब्दों से बुद्धिमान राजा सुलैम..."
9996,Police have arrested two people and apprehende...,पुलिस ने युवकों का पीछा कर दो युवकों को हिरासत...
9997,"""The annual production of poultry meat in 1991...",में मुर्गीपालन से प्राप्त मांस तथा गाद का अनुम...
9998,Step 1: Visit the official websites rsosapp.ra...,सबसे पहले ऑफिशियल वेबसाइट education. rajasthan...
9999,Anil Ambanis Reliance Group has sued news chan...,डिस्क्लेमर : अनिल अंबानी के रिलायंस ग्रुप ने N...

In [9]:
# Keep only those words count whose sentences fall within the range of 5 to 50 in both languages.

#count english:
processed_df['Word Count(English)'] = processed_df['English Sentences'].astype(str).str.split().str.len()



#count hindi:
processed_df['Word Count(Hindi)'] = processed_df['Hindi Sentences'].astype(str).str.split().str.len()


# processed_df

#Filter English:
processed_df = processed_df[(processed_df['Word Count(English)']>=5) & (processed_df['Word Count(English)'] <=50)]

#Filter Hindi:
processed_df = processed_df[(processed_df['Word Count(Hindi)']>=5) & (processed_df['Word Count(Hindi)'] <=50)]

processed_df

,English Sentences,Hindi Sentences,Word Count(English),Word Count(Hindi)
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19
...,...,...,...,...
9995,"With these few, well - chosen words, wise King...","इन चंद, चुनिंदा शब्दों से बुद्धिमान राजा सुलैम...",30,38
9996,Police have arrested two people and apprehende...,पुलिस ने युवकों का पीछा कर दो युवकों को हिरासत...,10,14
9997,"""The annual production of poultry meat in 1991...",में मुर्गीपालन से प्राप्त मांस तथा गाद का अनुम...,24,24
9998,Step 1: Visit the official websites rsosapp.ra...,सबसे पहले ऑफिशियल वेबसाइट education. rajasthan...,9,10
9999,Anil Ambanis Reliance Group has sued news chan...,डिस्क्लेमर : अनिल अंबानी के रिलायंस ग्रुप ने N...,27,23

In [10]:
# Retain only those word pairs where the word count difference lies within the range of -10 to +10.

processed_df['Difference between Word Count(English) and Word Count(Hindi)'] = processed_df['Word Count(English)'] - processed_df['Word Count(Hindi)']


processed_df = processed_df[(processed_df['Difference between Word Count(English) and Word Count(Hindi)']>=-10) & (processed_df['Difference between Word Count(English) and Word Count(Hindi)']<=10)]

processed_df

,English Sentences,Hindi Sentences,Word Count(English),Word Count(Hindi),Difference between Word Count(English) and Word Count(Hindi)
0,"However, Paes, who was partnering Australia's ...",आस्ट्रेलिया के पाल हेनली के साथ जोड़ी बनाने वाल...,23,28,-5
1,"Whosoever desires the reward of the world, wit...",और जो शख्स (अपने आमाल का) बदला दुनिया ही में च...,26,35,-9
2,"""The value of insects in the biosphere is enor...","जैव-मंडल में कीड़ों का मूल्य बहुत है, क्योंकि ...",21,22,-1
3,Mithali To Anchor Indian Team Against Australi...,आस्ट्रेलिया के खिलाफ वनडे टीम की कमान मिताली को,9,9,0
4,After the assent of the Honble President on 8t...,"8 सितम्‍बर, 2016 को माननीय राष्‍ट्रपति की स्‍व...",18,19,-1
...,...,...,...,...,...
9995,"With these few, well - chosen words, wise King...","इन चंद, चुनिंदा शब्दों से बुद्धिमान राजा सुलैम...",30,38,-8
9996,Police have arrested two people and apprehende...,पुलिस ने युवकों का पीछा कर दो युवकों को हिरासत...,10,14,-4
9997,"""The annual production of poultry meat in 1991...",में मुर्गीपालन से प्राप्त मांस तथा गाद का अनुम...,24,24,0
9998,Step 1: Visit the official websites rsosapp.ra...,सबसे पहले ऑफिशियल वेबसाइट education. rajasthan...,9,10,-1
9999,Anil Ambanis Reliance Group has sued news chan...,डिस्क्लेमर : अनिल अंबानी के रिलायंस ग्रुप ने N...,27,23,4

In [11]:
# Final Output:
'''
English Sentences
Hindi Sentences
Word Count (English)
Word Count (Hindi)
Difference between Word Count (English) and Word Count (Hindi)

'''

final_coloums =[
    'English Sentences',
    'Hindi Sentences',
    'Word Count(English)',
    'Word Count(Hindi)',
    'Difference between Word Count(English) and Word Count(Hindi)'
]

final_df = processed_df[final_coloums]
# final_df

final_df.to_excel("iitp_nlp_satyam.xlsx")

In [ ]:
# ASS2: Translation
import torch
from transformers import pipeline
from tqdm import tqdm

model_id = "meta-llama/Llama-3.2-3B"

pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

pipe("The key to life is")

config.json:   0%|          | 0.00/844 [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

[transformers] Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
import torch
from transformers import pipeline

model_id = "meta-llama/Llama-3.2-3B-Instruct"
pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]
outputs = pipe(
    messages,
    max_new_tokens=256,
)
print(outputs[0]["generated_text"][-1])